#%RAML 1.0
title: simple object
types:
  Person:
    properties:
      name: string
      email:
        type: string
        pattern: ^.+@.+\..+$
      age:
        type: integer
        minimum: 0
  Org:
    type: Person[]

/orgs:
  /{orgId}:
    /persons:
      post:
        description: create a new person
        body:
          application/json:
            type: Person
      /{personId}:
        get:
          description: get a specific person